AllCops:
  NewCops: enable

# Configuration parameters: AllowedParentClasses.
Lint/MissingSuper:
  Exclude:
    - 'main.rb'

Style/OptionalBooleanParameter:
  Enabled: false

Metrics/ClassLength:
  Max: 999 # ridiculous

# Configuration parameters: AllowedMethods, AllowedPatterns, CountRepeatedAttributes.
Metrics/AbcSize:
  Max: 999 # lol

# Configuration parameters: CountComments, CountAsOne, AllowedMethods, AllowedPatterns.
Metrics/MethodLength:
  Max: 50

# Configuration parameters: MinNameLength, AllowNamesEndingInNumbers, AllowedNames, ForbiddenNames.
# AllowedNames: as, at, by, cc, db, id, if, in, io, ip, of, on, os, pp, to
Naming/MethodParameterName:
  Enabled: false

# Configuration parameters: AllowedConstants.
Style/Documentation:
  Enabled: false

# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: always, always_true, never
Style/FrozenStringLiteralComment:
  Enabled: false

# This cop supports unsafe autocorrection (--autocorrect-all).
Style/InfiniteLoop:
  Enabled: false

# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: short, verbose
# Style/PreferredHashMethods:
#   Exclude:
#     - 'render.rb'

# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: Mode.
Style/StringConcatenation:
  Exclude:
    - 'scratch/curses.rb'

# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, AllowedPatterns.
# URISchemes: http, https
Layout/LineLength:
  Enabled: false
